services:
  database:
    build:
      context: ./database
    container_name: database
    environment:
      POSTGRES_USER: neo
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: flask_db
    ports:
    - "5432:5432"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    networks:
    - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
    - "5000:5000"
    networks:
    - app-network
    depends_on:
      - database

networks:
  app-network:
